version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    command: start --spi-sticky-session-encoder-infinispan-should-attach-route=false
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8081
      KC_PROXY_HEADERS: forwarded
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"  # Handled by Nginx
      KC_HOSTNAME: https://idp.behsacorp.com
      KC_HOSTNAME_ADMIN: https://idp.behsacorp.com
      KC_CACHE_CONFIG_FILE: cache-ispn-jdbc-ping.xml
      PROXY_ADDRESS_FORWARDING: true
      KC_SPI_STICKY_SESSION_ENCODER_INFINISPAN_SHOULD_ATTACH_ROUTE: false
    ports:
      - "8085:8085"
      - "7600:7600"
      - "7800:7800"
      - "57800:57800"
    extra_hosts:
      - "ipa01.idm.behsacorp.com:172.18.99.234"
    volumes:
      - ./themes/behsa:/opt/keycloak/themes/behsa
      - ./discovery:/opt/jboss/tools/cli/jgroups/discovery/
      - ./discovery/cache-ispn-jdbc-ping2.xml:/opt/keycloak/conf/cache-ispn-jdbc-ping.xml

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8085:8085"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # If you have SSL certificates
    depends_on:
      - keycloak
    extra_hosts:
      - "ipa01.idm.behsacorp.com:172.18.99.234"