version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    command: start
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HTTP_PORT: ${KC_HTTP_PORT}
      KC_PROXY_HEADERS: forwarded
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"  # Handled by Nginx
      KC_HOSTNAME: https://idp.behsacorp.com
      KC_HOSTNAME_ADMIN: https://idp.behsacorp.com
      JGROUPS_DISCOVERY_EXTERNAL_IP: 172.18.99.234
      JGROUPS_DISCOVERY_PROTOCOL: TCPPING
      JGROUPS_DISCOVERY_PROPERTIES: '172.18.99.234[57800],172.18.99.233[57800]'
    ports:
      - "8085:8080"
      - "7600:7600"
      - "57800:57800"
    depends_on:
      - postgres
    volumes:
      - ./themes/behsa:/opt/keycloak/themes/behsa
      - ./discovery/TCPPING.cli:/opt/jboss/tools/cli/jgroups/discovery/TCPPING.cli
      #- ./discovery:/opt/jboss/tools/cli/jgroups/discovery/
      - ./cache-ispn-jdbc-ping.xml:/opt/keycloak/conf/cache-ispn-jdbc-ping.xml
    extra_hosts:
      - "ipa01.idm.behsacorp.com:172.18.99.234"
    network_mode: "host"

  postgres:
    image: docker.arvancloud.ir/postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # This line adds the volume
    networks:
      - keycloak-net
    ports:
      - "5432:5432"

networks:
  keycloak-net:
    driver: bridge
