version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HTTP_PORT: ${KC_HTTP_PORT}
      KC_PROXY_HEADERS: forwarded
      KC_PROXY: edge
      JGROUPS_DISCOVERY_EXTERNAL_IP: 172.18.99.234
      JGROUPS_DISCOVERY_PROTOCOL: TCPPING
      JGROUPS_DISCOVERY_PROPERTIES: initial_hosts="172.18.99.234[7600],172.18.99.233[7600]"
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"  # Handled by Nginx
      KC_HOSTNAME: pid.behsacorp.com
      KC_HOSTNAME_ADMIN: pid.behsacorp.com
      KC_HOSTNAME_STRICT_HTTPS: "true"
    command:
      - /bin/sh
      - -c
      - |
        /opt/keycloak/bin/kc.sh build
        /opt/keycloak/bin/kc.sh start --optimized
    ports:
      - "8085:8080"
      - "7600:7600"
    depends_on:
      - postgres
    networks:
      - keycloak-net

  postgres:
    image: docker.arvancloud.ir/postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # This line adds the volume
    networks:
      - keycloak-net

networks:
  keycloak-net:
    driver: bridge
