version: '3.8'

services:


  ldap:
    image: docker.arvancloud.ir/osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
    ports:
      - "389:389"
      - "636:636"
    networks:
      - keycloak-net

  ldap-admin:
    image: docker.arvancloud.ir/osixia/phpldapadmin:0.9.0
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${PHPLDAPADMIN_LDAP_HOSTS}
      PHPLDAPADMIN_HTTPS: ${PHPLDAPADMIN_HTTPS}
    ports:
      - "8081:80"
    depends_on:
      - ldap
    networks:
      - keycloak-net

networks:
  keycloak-net:
    driver: bridge
